language: c
dist: xenial
services:
  - docker
env:
  matrix:
    - TEST=pts/pgbench
    - TEST=pts/build-linux-kernel
install: docker pull jasonmp85/phoronix-tester
script:  docker run jasonmp85/phoronix-tester "${TEST}"
