language: c
dist: xenial
before_install: sudo apt-get install -y phoronix-test-suite
script:
  - PTS_SILENT_MODE=1 phoronix-test-suite benchmark pts/compilation
  - PTS_SILENT_MODE=1 phoronix-test-suite benchmark pts/database
